<?php
  function custom_form_form_alter(&$form, &$form_state, $form_id) {

    if($form_id == 'edit_body_und_0_format__2') {
      $form['author']['#access'] = 0;
      $form['options']['#access'] = 0;
      $form['comment_settings']['#access'] = 0;
      $form['revision_information']['#access'] =0;

      // print '<pre>';
      // print_r($form);
      // print '</pre>';
      // exit;
    }


  }
